### ISSUE TITLE
lapis_lazuli_ore needs to be modified to lapis_ore

### ISSUE THREAD

**Issue by empyrealtear** [Auxilor/EcoSkills#163]
Hello, when I used the enchanted silk_touch to dig the lapis_ore, I could never trigger the spelunking effect. After read your code, I think `lapis_lazuli_ore` needs to be modified to `lapis_ore`.

- [spelunking.yml](https://github.com/Auxilor/EcoSkills/blob/master/eco-core/core-plugin/src/main/resources/effects/spelunking.yml)

```yml
name: "Spelunking"
...

effects:
  - id: multiply_drops # Base Multiplier
    ...
    filters:
      player_placed: false
      blocks:
        ...
        - "lapis_lazuli_ore" -> "lapis_ore"
        - "deepslate_lapis_lazuli_ore" -> "deepslate_lapis_ore"
        ...

- id: multiply_drops # Bonus Multiplier
    ...
    filters:
      player_placed: false
      blocks:
        ...
        - "lapis_lazuli_ore" -> "lapis_ore"
        - "deepslate_lapis_lazuli_ore" -> "deepslate_lapis_ore"
        ...
```
