### ISSUE TITLE
Potion Master bug

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/EcoSkills#33]
**Describe the bug**
For some reason the Potion Master make it so it gives the level higher of the brewed potion when the description isn't saying it does this. It's also doing it even when on level 0

**To Reproduce**
1. Brew a strength II potion
2. you will receive a strength III potion

**Expected behavior**
It shouldn't make potions of a higher level instantly

**Screenshots**
Config:
```
potionmaster:
  description: "&8Brewed potions last &a%percent_more%%&8 longer"

  # The percent more time for potions to last for each level of the effect
  percent-more-per-level: 4

  # The lore to add to indicate a duration buff
  lore:
    - ""
    - "&fPotionmaster Buff:"
    - "&8» &f+&e%seconds%&f Seconds"

  # Disabled worlds
  disabled-in-worlds: [ ]
```
  
**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
Eco: 6.20.4
EcoSkills: 1.20.9
**Additional context**
